# UTS-2 My Songs for You ♫（´▽｀）♪

Belakangan ini aku lagi suka banget sama Oasis. Salah satu lagu favoritku adalah Don't Go Away. Setiap kali kudengar, lagu itu seperti mengulang kembali semua rasa yang kutemukan pada seseorang yang sangat aku cintai dan selalu ada di sisiku.

Lagu itu bercerita tentang takut kehilangan, tentang seseorang yang ingin waktu berhenti sejenak agar orang yang dicintainya tak pergi. Tentang hal-hal sederhana yang justru paling sulit diungkapkan: “tetaplah di sini, cukup itu saja.”

Dari situ, aku terinspirasi untuk menulis lagu yang punya makna serupa. Sebuah cara kecil untuk menyimpan perasaan yang tak selalu bisa disampaikan dengan kata-kata.

p.s. lagu ini pernah aku selipkan di surat pertamaku untuknya.

## **Stay a Little While**

*Inspired by “Don’t Go Away” by Oasis*

Lyrics and composition by Rachel Elnora

Key: C Major

<br>

[Verse 1]

Cold night turns to morning, the sky’s a shade of grey

And your name caught in my mind

While the world keeps turning, I watch it fade away

Things I meant got left behind

<br>

[Pre-Chorus]

I don’t wanna lose you when the lights go down

I don’t wanna watch you when you’re not around

<br>

[Chorus]

So stay a little while, say what you feel

Say that you’ll stay for more than a while

You’re part of my days, ‘cause I need more time

Yes, I need more time just to make you smile

<br>

[Verse 2]

Blame my hesitation, the words I couldn’t say

All dreams we’ve left inside

Blame the constellations, they took your gaze away

Left my heart a step behind

<br>

[Pre-Chorus]

I still wanna find you when the rain falls down

I still wanna hold you when there’s no sound

<br>

[Chorus]

So stay a little while, say what you feel

Say that you’ll stay for more than a while

You’re part of my days, ‘cause I need more time

Yes, I need more time just to make you smile

<br>

[Bridge]

Me and you, what’s going on?

Maybe love’s just learning to be strong

<br>

[Chorus] (Reprise)

So stay a little while, say what you feel

Say that you’ll stay for more than a while

You’re part of my days, ‘cause I need more time

Yes, I need more time just to make you smile

Yes, I need more time just to make you smile

Yes, I need more time just to make you smile

<br>

So stay a little while

<iframe style="border-radius:12px" 
src="https://open.spotify.com/track/3MCuDi4gQrf7Xms8lTpTAx?si=6f2788e7e60c4d10" 
width="100%" height="152" frameBorder="0" 
allowfullscreen="" 
allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" 
loading="lazy"></iframe>
